### ISSUE TITLE
Crash when a client connects to a server with no map running

### ISSUE THREAD

**Issue by SamVanheer** [ValveSoftware/halflife#1742]
When a client connects to a server that does not have any map running, the server crashes.

Backtrace:
#0  0xf780eae8 in BSecure (this=<optimized out>) at ../engine/sv_steam3.h:72
#1  Steam_GSBSecure () at ../engine/sv_steam3.cpp:1033
#2  0xf77dec35 in SVC_GetChallenge () at ../engine/sv_main.c:3264
#3  0xf77e8825 in SV_HandleRconPacket () at ../engine/sv_main.c:9062
#4  SV_CheckForRcon () at ../engine/sv_main.c:9153
#5  0xf77b4ea2 in _Host_Frame (time=0,00113811297) at ../engine/host.c:1408
#6  0xf77b5252 in Host_Frame (time=0,00113811297, iState=1,

```
stateInfo=0xffffce4c) at ../engine/host.c:1522
```
#7  0xf77d98dc in CEngine::Frame (this=0xf78706a0 <g_Engine>)

```
at ../engine/sys_engine.cpp:245
```
#8  0xf77d6c43 in RunFrame (this=<optimized out>)

```
at ../engine/sys_dll2.cpp:1235
```
#9  CDedicatedServerAPI::RunFrame (

```
this=0xf786bd00 <__g_CDedicatedServerAPI_singleton>)
at ../engine/sys_dll2.cpp:1226
```
#10 0x08049c65 in RunServer () at ../dedicated/sys_ded.cpp:766
#11 0x08049472 in main (argc=1, argv=0xffffd084)

```
at ../dedicated/sys_ded.cpp:1146
```

SVC_GetChallenge calls Steam_GSBSecure, which in turn accesses SteamGameServer.

There's a function called SteamGameServer_Init. It gets called in map, changelevel, restart and reload command handlers. Since no map has started, it hasn't been initialized.

**Comment by SamVanheer** [comment]
Duplicate of #1653. You can see that the server is started with no map so the cause is the same.
