### ISSUE TITLE
Segfault  

### ISSUE THREAD

**Issue by leonid9851** [ValveSoftware/halflife#2627]
Hi there. Here I'm again and I have a problem with the world... I mean world's object as I can read the debug's logs:

```
CRASH: Thu Jul 25 19:42:44 MSK 2019
Start Line: ./hlds_linux -game cstrike +ip x.x.x. +port xxxxx +map jail_xmf +maxplayers 20 -condebug -debug -insecure -timeout 60 +sys_ticrate 10000 -noipx -norestart -pidfile game.pid
[New LWP 11472]
[New LWP 11485]
[New LWP 11482]
[New LWP 11489]
[New LWP 11491]
[New LWP 11517]
[New LWP 21201]
[New LWP 20283]
[New LWP 11483]
[New LWP 21717]
[New LWP 11490]
[New LWP 11492]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./hlds_linux -game cstrike +ip x.x.x.x +port xxxxx +map jail_xmf +maxplaye'.
Program terminated with signal 11, Segmentation fault.
#0  0xf6f3b130 in SV_SingleClipMoveToEntity (ent=0xf35d9ef8, start=0xffde5894, mins=0xf6f93344 <vec3_origin>, maxs=0xf6f93344 <vec3_origin>, end=0xffde559c, trace=0xffde5344) at ../engine/world.c:965
#0  0xf6f3b130 in SV_SingleClipMoveToEntity (ent=0xf35d9ef8, start=0xffde5894, mins=0xf6f93344 <vec3_origin>, maxs=0xf6f93344 <vec3_origin>, end=0xffde559c, trace=0xffde5344) at ../engine/world.c:965
#1  0xf6f3baba in SV_ClipMoveToEntity (end=<optimized out>, maxs=<optimized out>, mins=<optimized out>, start=<optimized out>, ent=0xf35d9ef8) at ../engine/world.c:1089
#2  SV_ClipToLinks (node=0xf73ce9a0 <sv_areanodes+736>, clip=0xffde549c) at ../engine/world.c:1232
#3  0xf6f3ba7d in SV_ClipToLinks (node=0xf73ce8c0 <sv_areanodes+512>, clip=0xffde549c) at ../engine/world.c:1254
#4  0xf6f3c4c3 in SV_Move (start=0xffde5894, mins=0xf6f93344 <vec3_origin>, maxs=0xf6f93344 <vec3_origin>, end=0xffde58a0, type=0, passedict=0xf35c9404, monsterClipBrush=false) at ../engine/world.c:1461
#5  0xf6f08098 in PF_traceline_Shared (ent=<optimized out>, nomonsters=0, v2=0xffde58a0, v1=0xffde5894) at ../engine/pr_cmds.c:494
#6  PF_traceline_DLL (v1=0xffde5894, v2=0xffde58a0, fNoMonsters=0, pentToSkip=0xf35c9404, ptr=0xffde582c) at ../engine/pr_cmds.c:504
#7  0xf2f2b3d2 in ?? () from cstrike/addons/amxmodx/modules/fun_amxx_i386.so
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
offset = {0, 0, -nan(0x5e58cc)}
start_l = {-nan(0x5e57c0), 1.40129846e-45, 1.40129846e-45}
end_l = {1.01877057e-15, -nan(0x5e5418), -3.12871023e+33}
hull = <optimized out>
pmodel = <error reading variable pmodel (Cannot access memory at address 0x30940)>
numhulls = <optimized out>
i = <optimized out>
rotated = <optimized out>
From        To          Syms Read   Shared Object Library
0xf7677914  0xf76bdc78  Yes         ./libstdc++.so.6
0xf7625a90  0xf762697c  Yes (*)     /lib/libdl.so.2
0xf760e780  0xf761a857  Yes (*)     /lib/libpthread.so.0
0xf7460320  0xf75a691b  Yes (*)     /lib/libc.so.6
0xf740b460  0xf7435c06  Yes (*)     /lib/libm.so.6
0xf73f3e04  0xf7403490  Yes         ./libgcc_s.so.1
0xf77148a0  0xf772f261  Yes (*)     /lib/ld-linux.so.2
0xf6ed7600  0xf6f5b5ac  Yes         /game/engine_i486.so
0xf6e7d5c0  0xf6e87d74  Yes (*)     ./libsteam_api.so
0xf6e73900  0xf6e76dca  Yes (*)     /lib/librt.so.1
0xf6e59f40  0xf6e6b3f8  Yes (*)     /game/filesystem_stdio.so
0xf5baa1c0  0xf6923b04  Yes (*)     /.steam/sdk32/steamclient.so
0xf32c2df0  0xf32d7614  Yes         /game/./cstrike/addons/metamod/metamod.so
0xf3087370  0xf31ab3a0  Yes         /game/cstrike/dlls/cs.so
0xf2f48a00  0xf2fa8768  Yes (*)     /game/cstrike/addons/amxmodx/dlls/amxmodx_mm_i386.so
0xf2f29c10  0xf2f2cc98  Yes (*)     cstrike/addons/amxmodx/modules/fun_amxx_i386.so
0xf2f180d0  0xf2f23478  Yes (*)     cstrike/addons/amxmodx/modules/engine_amxx_i386.so
0xf2edfc50  0xf2f0c4a8  Yes (*)     cstrike/addons/amxmodx/modules/fakemeta_amxx_i386.so
0xf762bd90  0xf762cd08  Yes (*)     cstrike/addons/amxmodx/modules/sockets_amxx_i386.so
0xf2eb8350  0xf2ec0fc8  Yes (*)     cstrike/addons/amxmodx/modules/regex_amxx_i386.so
0xf2eab490  0xf2eb2d78  Yes (*)     cstrike/addons/amxmodx/modules/nvault_amxx_i386.so
0xf2e77870  0xf2ea30b8  Yes (*)     cstrike/addons/amxmodx/modules/hamsandwich_amxx_i386.so
0xf2dfb9d0  0xf2e24618  Yes (*)     cstrike/addons/amxmodx/modules/orpheu_amxx_i386.so
0xf2bdd8c0  0xf2d8b571  Yes (*)     /game/cstrike/addons/vtc/VoiceTranscoder.so
                        Yes (*)     /game/cstrike/addons/processcmds/processcmds_mm_i386.so
                        Yes (*)     /lib/libvectcc.so.8
0xf2afad70  0xf2b359b8  Yes (*)     ./libssl.so.1.0.0
0xf2975040  0xf2a77328  Yes (*)     ./libcrypto.so.1.0.0
0xf2916860  0xf29233a4  Yes (*)     /lib/libz.so.1
0xf2668110  0xf2693650  Yes (*)     /game/cstrike/addons/dproto/dproto_i386.so
0xf23a9490  0xf2439228  Yes (*)     cstrike/addons/amxmodx/modules/mysql_amxx_i386.so
0xf224c220  0xf22529d8  Yes (*)     cstrike/addons/amxmodx/modules/cstrike_amxx_i386.so
0xee616200  0xef4af3c4  Yes (*)     ./steamclient.so
0xf22c9670  0xf233f020  Yes (*)     ./crashhandler.so
0xf22b0a50  0xf22b7fb9  Yes (*)     /lib/libnss_files.so.2
0xf22a8c00  0xf22ac06e  Yes (*)     /lib/libnss_dns.so.2
0xf22906a0  0xf229f694  Yes (*)     /lib/libresolv.so.2
0xf2287e60  0xf2288b70  Yes (*)     /lib/libstdvc++.so.1
0xf227d380  0xf227e428  Yes (*)     /lib/libvectc++.so.7
(*): Shared library is missing debugging information.
Stack level 0, frame at 0xffde52cc:
 eip = 0xf6f3b130 in SV_SingleClipMoveToEntity (../engine/world.c:965); saved eip 0xf6f3baba
 called by frame at 0xffde539c
 source language c.
 Arglist at 0xffde51ec, args: ent=0xf35d9ef8, start=0xffde5894, mins=0xf6f93344 <vec3_origin>, maxs=0xf6f93344 <vec3_origin>, end=0xffde559c, trace=0xffde5344
 Locals at 0xffde51ec, Previous frame's sp is 0xffde52cc
 Saved registers:
  ebx at 0xffde52b8, ebp at 0xffde52c4, esi at 0xffde52bc, edi at 0xffde52c0, eip at 0xffde52c8
End of crash report
----------------------------------------------
```

Modules:

> Fun 1.8.2 AMX Mod X Dev Team running
> Engine 1.8.2 AMX Mod X Dev Team running
> FakeMeta 1.8.2 AMX Mod X Dev Team running
> Sockets 1.8.2 HLSW Dev Team running
> RegEx 1.8.2 AMX Mod X Dev Team running
> nVault 1.8.2 AMX Mod X Dev Team running
> Ham Sandwich 1.8.2 AMX Mod X Dev Team running
> Orpheu 2.6.3 joaquimandrade & Ar running
> MySQL 1.8.2 AMX Mod X Dev Team running
> CStrike 1.8.2 AMX Mod X Dev Team running

HLDS Build is 7882.

Do you have any ideas? Thx for the attention btw.

**Comment by afwn90cj93201nixr2e1re** [comment]
Is that goldsrc bug? No. Check fun module, from stacktrace.

**Comment by RauliTop** [comment]
Probably it should be posted at alliedmodders forums instead here.

**Comment by leonid9851** [comment]
Yeah, I've got it .
